---
title: "Resident Engagement Scores 2016-2017"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(forcats)
library(themebg)
library(plotly)

scores <- read_rds("../data/final/scores.Rds")
```

```{r, fig.width=8, fig.height=7, fig.cap="Aggregate score for each question. Solid line indicates overall score, dashed line indicates overall employee score."}
p <- scores %>%
    arrange(Score) %>%
    mutate_at("Item", fct_inorder) %>%
    ggplot(aes(x = Item, y = Score)) +
    geom_bar(aes(fill = Domain), stat = "identity") +
    geom_hline(yintercept = 3.62, color = "grey35") +
    geom_hline(yintercept = 3.62 + 0.65, color = "grey20", linetype = "dashed") +
    scale_fill_brewer(palette = "Dark2") +
    coord_flip() +
    theme_bg(yticks = FALSE) +
    theme(legend.position = c(0, 1), 
          legend.justification = c(1, 0),
          legend.direction = "horizontal",
          plot.margin = unit(c(5, 1, 0.5, 0.5), "lines"))

p
# ggplotly(p, dynamicTicks = TRUE)
```

